### ISSUE TITLE
Is actually a forkbomb when run from npm prepublish

### ISSUE THREAD

**Issue by apaleslimghost** [quarterto/npm-package-integrity#1]
`npm-package-integrity` runs `npm pack` runs `npm prepublish` runs `npm-package-integrity`...

**Comment by keithamus** [comment]
I believe you can look at `process.env.npm_config_argv` to find out what command was actually run.

**Comment by apaleslimghost** [comment]
[that's how i fixed it](https://github.com/quarterto/npm-package-integrity/commit/351d97ceda84f2f9bf8f056acf25764bef411c85#diff-6972a20a787e7b97a27cf56365ddde9dR21)
